name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Change this to the main branch of your repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Change this to your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Install Express
      run: npm install express

    - name: Run tests
      run: npm app.js

    - name: Deploy to production
      if: success()
      run: |
        pkill -f "node app.js"
        # Add your deployment steps here, such as deploying to a server, cloud platform, or hosting service.
